version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp build/ s3://qweasdzxciopjklbnm/ 

artifacts:
  files:
    - '**/*'
